language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
matrix:
  exclude:
    - os: osx
      rust: beta
    - os: osx
      rust: nightly
    - os: windows
      rust: beta
    - os: windows
      rust: nightly
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - RUSTFLAGS='-F warnings' cargo build --verbose --all
  - RUSTFLAGS='-F warnings' cargo test --verbose --all
stages:
  - Check
  - Test
  - Deploy
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      script:
        - rustup component add clippy
        - RUSTFLAGS='-F warnings' cargo clippy --all --all-targets --all-features
    - stage: Deploy
      if: branch = master
      name: Deploy
      script:
        - |
            for crate in \
                    prelude \
                    algorithms; do
                cargo clean
                cd "${crate}" \
                    && cargo publish --token "${CARGO_PUBLISH_TOKEN}" \
                    && echo "Publish ${crate} is DONE." \
                    || echo "Failed to publish ${crate}."
                cd ..
            done
